// Datos del prototipo Gonflé.
// Todo lo que aparece aquí sale de los catálogos 2022, el brochure "Piensa en tu meta",
// los flyers recientes o la reunión con la gerente. Lo que no está confirmado va como null
// y la interfaz lo muestra como "Por confirmar".

const CONTACTO = {
  whatsapp: "573127576447",          // (+57) 312 757 6447 — aparece en todos los documentos
  telefono: "(+57) 312 757 6447",
  email: "gerencia@gonflegroup.com", // el más reciente (flyer 2026). Los catálogos 2022 usan @gonfle.com.co, dominio hoy perdido.
  ciudad: "Medellín, Antioquia",
  instagram: "https://www.instagram.com/gonfleoficial/",
};

const IMG = "assets/img/";

const LINEAS = [
  { id: "inflables", nombre: "Inflables publicitarios", corto: "Inflables",
    desc: "Arcos, réplicas de producto, muñecos, disfraces y juegos. A motor o sellados, fabricados a la medida de tu marca.",
    intro: "Los inflables se diseñan y fabrican por proyecto: cuéntanos la forma, el tamaño y la fecha, y te enviamos propuesta. Producción entre 8 y 15 días hábiles.",
    img: "hero-pantera.webp", cubre: true },
  { id: "pop", nombre: "Material POP y punto de venta", corto: "Material POP",
    desc: "Cenefas, cabezotes, banderines, golpeadores, manillas, banderas, carpas y pendones para que tu marca domine el punto de venta.",
    intro: "Producción litográfica y de material POP en volumen. Para manillas, cenefas y litografía trabajamos desde miles de unidades.",
    img: "pop-golpeadores.webp" },
  { id: "merch", nombre: "Merchandising personalizado", corto: "Merchandising",
    desc: "Vasos, caramañolas, gorras, bolsas, libretas, bolígrafos y paraguas marcados con tu logo. Incluye línea ecológica.",
    intro: "Todos los productos se entregan marcados con tu logo. El precio depende de la cantidad y de la técnica de marcación.",
    img: "m-caramanola-sport.webp" },
  { id: "textil", nombre: "Textil y dotaciones", corto: "Textil",
    desc: "Chaquetas, camisas, conjuntos antifluido, camisetas y gorras para vestir a tu equipo con tu marca.",
    intro: "Fabricamos y personalizamos prendas con los textiles de tu elección y te asesoramos según el uso.",
    img: "t-hoodie.webp", cubre: true },
  { id: "regalos", nombre: "Regalos y catering corporativo", corto: "Regalos y catering",
    desc: "Cajas de Navidad, kits para colaboradores y clientes, refrigerios, brunch y jornadas de bienestar.",
    intro: "Línea nueva. Las imágenes son ilustrativas mientras se produce la fotografía real de cajas y montajes.",
    img: "ia-regalos.webp", cubre: true, nuevo: true },
];

// ref: imagen tomada del catálogo 2022 (puede mostrar marcas de terceros o no ser un trabajo propio).
// ia: imagen generada con IA. sinFoto: producto mencionado por la gerente, sin imagen disponible.
const PRODUCTOS = [
  // ───────── Inflables (por proyecto)
  { id: "arco-inflable", linea: "inflables", nombre: "Arco inflable", img: "inf-arco.webp", ref: true, destacado: true, proyecto: true,
    desc: "Arco de entrada o meta para carreras, lanzamientos y ferias. Forma, medidas y gráfica según tu marca.",
    specs: { "Tipo": "Inflable a motor", "Medidas": "A la medida", "Usos": "Eventos, carreras, activaciones, puntos de venta", "Producción": "8 a 15 días hábiles" } },
  { id: "replica-producto", linea: "inflables", nombre: "Réplica gigante de producto", img: "inf-lata.webp", ref: true, destacado: true, proyecto: true,
    desc: "Botellas, latas, envases o empaques a gran escala, con el arte real de tu producto. Se pliegan para almacenar fácil.",
    specs: { "Tipo": "Inflable a motor o sellado", "Medidas": "A la medida, hasta 14 m de alto", "Usos": "Lanzamientos, trade marketing, exhibición exterior", "Producción": "8 a 15 días hábiles" } },
  { id: "muneco-inflable", linea: "inflables", nombre: "Muñeco o personaje de marca", img: "inf-muneco.webp", ref: true, proyecto: true,
    desc: "La mascota o personaje de tu marca convertido en un inflable imponente, diseñado sobre medida y en cualquier tamaño.",
    specs: { "Tipo": "Inflable a motor", "Medidas": "A la medida, hasta 14 m de alto", "Usos": "BTL, eventos, fachadas", "Producción": "8 a 15 días hábiles" } },
  { id: "disfraz-inflable", linea: "inflables", nombre: "Disfraz inflable (que camina)", img: "inf-disfraz.webp", ref: true, proyecto: true,
    desc: "Personajes inflables que una persona viste y mueve: recordación por gigantismo en activaciones y eventos.",
    specs: { "Tipo": "Inflable a motor portátil", "Medidas": "A la medida", "Usos": "Activaciones de marca, eventos, recorridos", "Producción": "8 a 15 días hábiles" } },
  { id: "carpa-inflable", linea: "inflables", nombre: "Carpa, túnel o domo inflable", img: "inf-carpa.webp", ref: true, proyecto: true,
    desc: "Estructuras inflables de marca para stands, zonas de experiencia y publicidad exterior.",
    specs: { "Tipo": "Inflable a motor", "Medidas": "A la medida", "Usos": "Ferias, stands, zonas de marca", "Producción": "8 a 15 días hábiles" } },
  { id: "juego-inflable", linea: "inflables", nombre: "Juego o inflable recreativo", img: "inf-juego.webp", ref: true, proyecto: true,
    desc: "Canchas, tiros al arco y juegos de marca para eventos al aire libre. Personalizables y adaptables al presupuesto.",
    specs: { "Tipo": "Inflable a motor", "Medidas": "A la medida", "Usos": "Eventos familiares, activaciones deportivas", "Producción": "8 a 15 días hábiles" } },
  { id: "cilindro-stand", linea: "inflables", nombre: "Cilindros, esferas y stands", img: "inf-stand.webp", ref: true, proyecto: true,
    desc: "Formas publicitarias para interior y exterior: cilindros, esferas, huracanes y stands inflables.",
    specs: { "Tipo": "Inflable a motor o sellado", "Medidas": "A la medida", "Usos": "Publicidad interior y exterior", "Producción": "8 a 15 días hábiles" } },

  // ───────── Material POP
  { id: "manillas", linea: "pop", nombre: "Manillas publicitarias", sinFoto: true, destacado: true,
    desc: "Manillas marcadas para eventos, control de acceso y campañas. Producción propia.",
    specs: { "Producción": "Propia", "Cantidad mínima": "Desde miles de unidades", "Marcación": "Por confirmar", "Materiales": "Por confirmar" } },
  { id: "cenefas-cabezotes", linea: "pop", nombre: "Cenefas y cabezotes de góndola", sinFoto: true,
    desc: "Piezas litográficas para vestir góndolas y exhibiciones en retail.",
    specs: { "Producción": "Litografía", "Cantidad mínima": "Desde miles de unidades", "Formato": "A la medida de la góndola" } },
  { id: "banderines", linea: "pop", nombre: "Banderines", img: "pop-banderines.webp", ref: true, destacado: true,
    desc: "Banderines impresos para ambientar puntos de venta, bares y eventos.",
    specs: { "Uso": "Punto de venta, eventos", "Formato": "A la medida", "Cantidad mínima": "Por confirmar" } },
  { id: "golpeadores", linea: "pop", nombre: "Golpeadores inflables", img: "pop-golpeadores.webp", ref: true,
    desc: "Aplaudidores sellados con tu marca para eventos deportivos y activaciones.",
    specs: { "Tipo": "Inflable sellado (alta frecuencia)", "Uso": "Eventos, estadios, activaciones", "Cantidad mínima": "Por confirmar" } },
  { id: "botella-replica", linea: "pop", nombre: "Réplica sellada de producto", img: "pop-botella.webp", ref: true,
    desc: "Réplicas de botella o envase en inflable sellado para exhibición y obsequio.",
    specs: { "Tipo": "Inflable sellado (alta frecuencia)", "Uso": "Exhibición, obsequio promocional", "Cantidad mínima": "Por confirmar" } },
  { id: "banderas", linea: "pop", nombre: "Banderas publicitarias", img: "pop-banderas.webp", ref: true,
    desc: "Banderas tipo pétalo, cuadradas y tropezones para exterior y recorridos.",
    specs: { "Tipos": "Pétalo, cuadrada, tropezón", "Uso": "Exterior, puntos de venta, activaciones" } },
  { id: "carpas-kioscos", linea: "pop", nombre: "Carpas y kioscos", img: "pop-carpa.webp", ref: true,
    desc: "Carpas y kioscos impresos con tu marca para ferias y eventos.",
    specs: { "Uso": "Ferias, eventos, ventas en exterior", "Impresión": "Full color", "Medidas": "Por confirmar" } },
  { id: "portapendones", linea: "pop", nombre: "Portapendones y stand portátil", img: "pop-rollup.webp", ref: true,
    desc: "Pendones roll-up, tipo araña y stands portátiles listos para instalar.",
    specs: { "Tipos": "Roll-up, araña, stand portátil", "Uso": "Eventos, recepciones, puntos de venta" } },

  // ───────── Merchandising
  { id: "caramanola-sport-17", linea: "merch", nombre: "Caramañola Sport 17 oz, tapa clip", img: "m-caramanola-sport.webp", ref: true, destacado: true,
    desc: "Caramañola con tapa clip y pitillo, una de las referencias más prácticas para campañas y bienestar.",
    specs: { "Código": "3203014", "Material": "PVC y polipropileno", "Tamaño": "Ø 7,5 cm × 16,5 cm de alto", "Área de marcación": "Tampografía 4 × 4 cm · Serigrafía 8 × 25,5 cm · Etiqueta 8 × 24,5 cm" } },
  { id: "caramanola-cilindrica-24", linea: "merch", nombre: "Caramañola cilíndrica 24 oz", img: "m-caramanola-cil.webp", ref: true,
    desc: "Caramañola transparente de gran capacidad con amplia área de marcación.",
    specs: { "Código": "3203010", "Material": "PVC", "Tamaño": "Ø 7 cm × 25 cm de alto", "Área de marcación": "Tampografía 7 × 4,5 cm · Serigrafía 16 × 21 cm · Etiqueta 14 × 21,5 cm" } },
  { id: "caramanola-squash-26", linea: "merch", nombre: "Caramañola Squash 26 oz", img: "m-caramanola-squash.webp", ref: true,
    desc: "Botella deportiva flexible de 26 onzas.",
    specs: { "Código": "3203035", "Material": "Polietileno", "Tamaño": "Ø 6 cm × 23,5 cm de alto", "Área de marcación": "Serigrafía 7 × 23,5 cm · Etiqueta 13 × 23,5 cm" } },
  { id: "vaso-pitillo-16", linea: "merch", nombre: "Vaso con pitillo 16 oz", img: "m-vaso-pitillo.webp", ref: true, destacado: true,
    desc: "Vaso con tapa, asa y pitillo. Muy usado en eventos, bares y campañas de consumo.",
    specs: { "Material": "Polipropileno", "Tamaño": "Ø 8,5 cm × 13,5 cm de alto", "Área de marcación": "Tampografía 4,5 × 4,5 cm · Serigrafía 6 × 22 cm · Etiqueta 11,5 × 23 cm" } },
  { id: "vaso-redondo-11", linea: "merch", nombre: "Vaso redondo 11 oz", img: "m-vaso-redondo.webp", ref: true,
    desc: "Vaso plástico reutilizable para eventos y temporada.",
    specs: { "Código": "3216041", "Material": "Polipropileno", "Tamaño": "Ø 6,5 cm × 13 cm de alto", "Área de marcación": "Tampografía 3,5 × 3,5 cm · Serigrafía 9 × 18 cm" } },
  { id: "copa-champana", linea: "merch", nombre: "Copa champaña", img: "m-copa.webp", ref: true,
    desc: "Copa plástica para brindis, eventos y lanzamientos.",
    specs: { "Código": "3204011", "Material": "Poliestireno", "Tamaño": "Ø 7 cm × 14,5 cm de alto", "Área de marcación": "Tampografía 4 × 4 cm" } },
  { id: "yarda-32", linea: "merch", nombre: "Yarda 32 oz", img: "m-yarda.webp", ref: true,
    desc: "Yarda de 32 onzas, con o sin tapa, para eventos y bebidas de temporada.",
    specs: { "Material": "PVC", "Tamaño": "Ø 10 cm × 40 a 43 cm de alto", "Área de marcación": "Tampografía 4 × 4 cm" } },
  { id: "sanduchera", linea: "merch", nombre: "Sanduchera / portacomidas", img: "m-sanduchera.webp", ref: true,
    desc: "Portacomidas plástico con área amplia para marcación. Varias referencias y tamaños.",
    specs: { "Material": "Polipropileno", "Tamaño": "Según referencia (No. 3, 4, 7 y 8)", "Área de marcación": "Hasta 9,5 × 13 cm según referencia" } },
  { id: "gorra-neville", linea: "merch", nombre: "Gorra Neville, 6 paneles", img: "m-gorra-neville.webp", ref: true, destacado: true,
    desc: "Gorra de 6 paneles con visera indeformable, botón forrado, 4 ojetes bordados y cierre de hebilla metálica.",
    specs: { "SKU": "0023", "Material": "Algodón cepillado grueso", "Colores": "Amarillo, azul oscuro, azul rey, khaki, negro, rojo, verde esmeralda", "Marcación": "Bordado o screen", "Empaque": "200 unidades por caja" } },
  { id: "gorra-hanna", linea: "merch", nombre: "Gorra Hanna, tipo trucker", img: "m-gorra-hanna.webp", ref: true,
    desc: "Gorra de 5 paneles con frente fusionado y parte posterior en malla.",
    specs: { "SKU": "0020", "Material": "Poliéster y malla nylon", "Colores": "Más de 15 combinaciones", "Marcación": "Bordado, screen o sublimación", "Empaque": "200 unidades por caja" } },
  { id: "bolsa-kansas", linea: "merch", nombre: "Bolsa ecológica Kansas", img: "m-bolsa-kansas.webp", ref: true, cubre: true, eco: true, destacado: true,
    desc: "Bolsa reutilizable con doble agarradera y costuras reforzadas.",
    specs: { "SKU": "BOG010", "Material": "Kambrel", "Medidas": "38,2 × 29,5 × 9,7 cm · manija 34 cm", "Área de impresión": "22 × 15 cm aprox.", "Marcación": "Serigrafía hasta 2 tintas", "Empaque": "200 unidades por caja" } },
  { id: "slim-bag", linea: "merch", nombre: "Slim Bag ecológica", img: "m-slim-bag.webp", ref: true, eco: true,
    desc: "Bolsa ecológica plana para tiendas, mercados y eventos.",
    specs: { "Material": "Kambrel 80 g", "Medidas": "37 × 39,3 cm · manija 60 cm", "Área de impresión": "25 × 20 cm aprox.", "Marcación": "Screen 1 tinta", "Empaque": "200 unidades por caja" } },
  { id: "canguro-london", linea: "merch", nombre: "Canguro London", img: "m-canguro.webp", ref: true,
    desc: "Canguro en lona con dos bolsillos y cierre de cremallera. Producción nacional.",
    specs: { "SKU": "VDG031", "Material": "Lona poliéster 600D", "Medidas": "25 × 12 × 5,5 cm", "Marcación": "Screen, 10 cm", "Origen": "Producción nacional" } },
  { id: "libreta-eco", linea: "merch", nombre: "Libreta ecológica con bolígrafo", img: "m-libreta.webp", ref: true, eco: true, destacado: true,
    desc: "Set de libreta con 70 hojas, 5 juegos de memos adhesivos y bolígrafo. Tamaño aproximado A6.",
    specs: { "SKU": "OF0151", "Material": "Papel reciclado", "Medidas": "10 × 15,3 × 1,2 cm", "Marcación": "Tampografía 6 × 6 cm", "Colores": "Azul oscuro, rojo, negro, verde oscuro, naranja, amarillo" } },
  { id: "boligrafo-bamboo", linea: "merch", nombre: "Bolígrafo ecológico Mónaco", img: "m-boligrafo.webp", ref: true, eco: true,
    desc: "Bolígrafo ecológico con sistema retráctil.",
    specs: { "Material": "Bambú", "Tamaño": "14 cm de largo", "Marcación": "Por confirmar" } },
  { id: "paraguas-golf-27", linea: "merch", nombre: "Paraguas Golf 27\"", img: "m-paraguas.webp", ref: true,
    desc: "Paraguas tipo golf de apertura automática y cierre manual, 8 cascos.",
    specs: { "SKU": "PA 0137", "Material": "Pongee, mango en EVA", "Medidas": "27 pulgadas × 8 cascos", "Marcación": "Screen" } },

  // ───────── Textil
  { id: "dotacion-antifluido", linea: "textil", nombre: "Conjuntos antifluido y uniformes", img: "t-uniforme.webp", ref: true, cubre: true, destacado: true,
    desc: "Uniformes y conjuntos antifluido fabricados y marcados con la identidad de tu empresa.",
    specs: { "Prendas": "Conjuntos antifluido, camisas, pantalones, chaquetas", "Textil": "A elección, con asesoría", "Marcación": "Bordado, estampación", "Cantidad mínima": "Por confirmar" } },
  { id: "hoodies-chaquetas", linea: "textil", nombre: "Hoodies y chaquetas de marca", img: "t-hoodie.webp", ref: true, cubre: true,
    desc: "Prendas promocionales para equipos comerciales, eventos y campañas.",
    specs: { "Prendas": "Hoodies, chaquetas, camisetas", "Marcación": "Bordado, estampación, serigrafía", "Cantidad mínima": "Por confirmar" } },

  // ───────── Regalos y catering (línea nueva — imágenes IA)
  { id: "cajas-navidad", linea: "regalos", nombre: "Cajas de Navidad y regalos corporativos", img: "ia-regalos.webp", ia: true, cubre: true, destacado: true,
    desc: "Cajas personalizadas, anchetas y kits para colaboradores, clientes y proveedores, con el branding de tu empresa.",
    specs: { "Incluye": "Caja o empaque personalizado, tarjeta corporativa, productos a elección", "Presupuestos": "Económico, corporativo, premium y ejecutivo", "Cantidad mínima": "Por confirmar", "Cobertura de entrega": "Por confirmar" } },
  { id: "catering-empresarial", linea: "regalos", nombre: "Catering empresarial", img: "ia-catering.webp", ia: true, cubre: true,
    desc: "Desayunos, brunch, refrigerios, lunch, almuerzos y estaciones de alimentos para reuniones y eventos corporativos.",
    specs: { "Servicios": "Desayunos, brunch, refrigerios, lunch, almuerzos, estaciones", "Cantidad mínima": "Por confirmar", "Cobertura": "Por confirmar" } },
  { id: "semana-salud", linea: "regalos", nombre: "Semana de la Salud y Bienestar", img: "ia-bienestar.webp", ia: true, cubre: true,
    desc: "Refrigerios saludables, kits de bienestar y material de marca para jornadas internas.",
    specs: { "Incluye": "Refrigerios saludables, desayunos y almuerzos, kits de bienestar, actividades", "Cantidad mínima": "Por confirmar" } },
];

const NECESIDADES = [
  { t: "Lanzar o activar una marca", s: "Inflables, carpas y banderas que se ven desde lejos", f: "inflables", ico: "megafono" },
  { t: "Destacar en punto de venta", s: "Cenefas, cabezotes, banderines y exhibición", f: "pop", ico: "tienda" },
  { t: "Regalar con mi logo", s: "Vasos, gorras, bolsas, libretas y más", f: "merch", ico: "regalo" },
  { t: "Vestir a mi equipo", s: "Dotaciones y prendas de marca", f: "textil", ico: "camisa" },
  { t: "Cerrar el año con mi gente", s: "Cajas de Navidad, catering y bienestar", f: "regalos", ico: "estrella" },
];

const FAQS = [
  ["¿Cuál es la cantidad mínima?", "Depende del producto. En litografía, manillas y cenefas trabajamos desde miles de unidades. En merchandising y textil la cantidad mínima cambia según la referencia y la técnica de marcación: indícanos cuántas unidades necesitas y te confirmamos en la cotización."],
  ["¿Cómo se calcula el precio?", "El precio por unidad baja a medida que sube la cantidad y depende del producto, la técnica de marcación y el número de tintas. Por eso no publicamos una lista de precios: te enviamos una cotización a la medida."],
  ["¿Cuánto tarda la producción?", "Los inflables se producen en 8 a 15 días hábiles. Para los demás productos el tiempo depende de la cantidad y la marcación, y se confirma en la cotización. Acordamos la fecha contigo y no prometemos entregas por debajo del tiempo mínimo de producción."],
  ["¿Cómo debo enviar mi logo o arte?", "En formato editable de Adobe Illustrator (vectores). Si no lo tienes, cuéntanos y revisamos contigo cómo preparar el arte."],
  ["¿Cuál es la forma de pago?", "Se consigna el 50 % de anticipo para iniciar producción y el saldo según lo acordado con tu gerente de cuenta. Las cotizaciones tienen una validez de 10 días hábiles."],
  ["¿Hacen entregas fuera de Medellín?", "Estamos en Medellín y atendemos empresas en otras ciudades. La cobertura y el costo de envío se confirman en cada cotización."],
  ["¿Todos los productos van personalizados?", "Sí. No vendemos producto genérico de estantería: cada pedido se produce o se marca con la identidad de tu marca."],
];
